# Generated by Django 3.0.5 on 2020-05-02 15:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_number', models.CharField(max_length=512)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_accounts', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='used_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_transactions', to='app.BankAccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='app.BankAccount')),
            ],
        ),
    ]
