version: '2.3'

services:

    db_postgres:
        image: mdillon/postgis:11-alpine
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data

    web:
        depends_on:
            - db_postgres
        image: protyom/course_app:app
        restart: always
        volumes:
            - .:/app
        ports:
            - 80:80
        env_file:
            - .env
        environment:
            - C_FORCE_ROOT=true
        tty: true
        command: python3 /app/manage.py runserver 0.0.0.0:80

    redis:
        image: redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
          - ${REDIS_PORT}:6379
        volumes:
          - redisdata:/data

volumes:
    pgdata:
    redisdata: